# ==================== Wordapp/management/commands/populate_words.py ====================

from django.core.management.base import BaseCommand
from Wordapp.models import Word

class Command(BaseCommand):
    help = 'Populate database with sample words for WordOrbit game'

    def handle(self, *args, **kwargs):
        self.stdout.write(self.style.WARNING('Starting to populate words...'))
        
        words_data = [
            # ========== EASY WORDS (50) ==========
            ('CAT', 'A small domesticated carnivorous mammal with soft fur', 'easy', 
             'The cat sat on the mat and purred contentedly.'),
            ('DOG', 'A domesticated carnivorous mammal that typically has a long snout', 'easy', 
             'The dog barked loudly at the mailman.'),
            ('BIRD', 'A warm-blooded vertebrate animal with feathers and wings', 'easy', 
             'The bird flew high in the bright blue sky.'),
            ('FISH', 'An aquatic animal with gills and fins', 'easy', 
             'The colorful fish swam gracefully in the pond.'),
            ('TREE', 'A woody perennial plant with a trunk and branches', 'easy', 
             'The old oak tree provides shade on hot days.'),
            ('BOOK', 'A written or printed work consisting of pages', 'easy', 
             'I read an interesting book about adventure.'),
            ('HOUSE', 'A building for human habitation', 'easy', 
             'They live in a beautiful house by the lake.'),
            ('CAR', 'A road vehicle powered by an engine', 'easy', 
             'He drives a red sports car to work.'),
            ('SUN', 'The star around which the earth orbits', 'easy', 
             'The sun is shining brightly today.'),
            ('MOON', 'The natural satellite of the earth', 'easy', 
             'The full moon illuminated the night sky.'),
            ('STAR', 'A luminous celestial body', 'easy', 
             'We counted the stars in the night sky.'),
            ('RAIN', 'Water falling from clouds', 'easy', 
             'The rain fell gently on the garden.'),
            ('WIND', 'Natural movement of air', 'easy', 
             'The wind blew leaves across the yard.'),
            ('FIRE', 'Combustion producing heat and light', 'easy', 
             'The fire kept us warm on cold nights.'),
            ('WATER', 'A transparent liquid essential for life', 'easy', 
             'Clean water is important for health.'),
            ('APPLE', 'A round fruit with red or green skin', 'easy',
             'I ate a red apple for lunch.'),
            ('TABLE', 'A piece of furniture with a flat top', 'easy',
             'We sat at the table for dinner.'),
            ('CHAIR', 'A seat with a back for one person', 'easy',
             'Please sit in that comfortable chair.'),
            ('PHONE', 'A device for talking to people far away', 'easy',
             'My phone is ringing loudly.'),
            ('SMILE', 'A happy expression on the face', 'easy',
             'Her smile brightened the room.'),
            ('DOOR', 'A hinged barrier used to close an opening', 'easy',
             'Please close the door behind you.'),
            ('WINDOW', 'An opening in a wall fitted with glass', 'easy',
             'I looked through the window at the view.'),
            ('FLOWER', 'The seed-bearing part of a plant', 'easy',
             'The flower smells wonderful.'),
            ('CLOUD', 'A visible mass of water droplets in the sky', 'easy',
             'The cloud blocked the sun.'),
            ('GRASS', 'Vegetation consisting of short plants', 'easy',
             'The grass needs to be cut.'),
            ('SHOE', 'A covering for the foot', 'easy',
             'I need to tie my shoe.'),
            ('HAT', 'A shaped covering for the head', 'easy',
             'He wore a red hat.'),
            ('BALL', 'A round object used in games', 'easy',
             'The children played with a ball.'),
            ('CAKE', 'A sweet baked dessert', 'easy',
             'We had chocolate cake for dessert.'),
            ('MILK', 'A white liquid produced by mammals', 'easy',
             'I drink milk every morning.'),
            ('BREAD', 'Food made from flour and water', 'easy',
             'Fresh bread smells delicious.'),
            ('BUTTER', 'A dairy product made from milk', 'easy',
             'I spread butter on my toast.'),
            ('CHEESE', 'A food made from pressed milk curds', 'easy',
             'This cheese tastes amazing.'),
            ('RICE', 'A cereal grain used as food', 'easy',
             'We eat rice with dinner.'),
            ('SOUP', 'A liquid food made by boiling', 'easy',
             'The hot soup warmed me up.'),
            ('SALT', 'A white crystalline substance for seasoning', 'easy',
             'Add a pinch of salt to taste.'),
            ('SUGAR', 'A sweet crystalline substance', 'easy',
             'Sugar makes coffee sweet.'),
            ('TEA', 'A hot drink made from leaves', 'easy',
             'I enjoy a cup of tea in the morning.'),
            ('COFFEE', 'A hot drink made from roasted beans', 'easy',
             'Coffee helps me wake up.'),
            ('JUICE', 'A liquid extracted from fruit', 'easy',
             'Orange juice is refreshing.'),
            ('BED', 'A piece of furniture for sleeping', 'easy',
             'I go to bed at nine.'),
            ('DESK', 'A table for reading or writing', 'easy',
             'My desk is very organized.'),
            ('LAMP', 'A device that produces light', 'easy',
             'Turn on the lamp please.'),
            ('CLOCK', 'An instrument for measuring time', 'easy',
             'The clock shows three o clock.'),
            ('KEY', 'A metal instrument for opening locks', 'easy',
             'I lost my house key.'),
            ('BOX', 'A container with flat sides', 'easy',
             'Put it in the box.'),
            ('BAG', 'A flexible container with an opening', 'easy',
             'She carried a red bag.'),
            ('CUP', 'A small bowl-shaped container for drinking', 'easy',
             'I need a cup of water.'),
            ('PLATE', 'A flat dish for holding food', 'easy',
             'Put your food on the plate.'),
            ('KNIFE', 'A cutting instrument with a blade', 'easy',
             'Use the knife carefully.'),
            
            # ========== MEDIUM WORDS (50) ==========
            ('PYTHON', 'A high-level programming language known for simplicity', 'medium', 
             'I am learning Python to build web applications.'),
            ('DJANGO', 'A Python web framework for rapid development', 'medium', 
             'Django makes web development much easier and faster.'),
            ('COMPUTER', 'An electronic device for processing data', 'medium', 
             'I work on my computer every day for projects.'),
            ('KEYBOARD', 'An input device with keys for typing', 'medium', 
             'The mechanical keyboard has a satisfying click.'),
            ('ELEPHANT', 'A large mammal with a trunk and tusks', 'medium', 
             'The elephant is the largest land animal on Earth.'),
            ('MOUNTAIN', 'A large natural elevation of the earth surface', 'medium', 
             'They climbed the mountain to see the sunrise.'),
            ('RAINBOW', 'An arc of colors formed in the sky', 'medium',
             'We saw a beautiful rainbow after the storm.'),
            ('CHOCOLATE', 'A sweet food made from cacao beans', 'medium', 
             'Dark chocolate is my favorite dessert treat.'),
            ('BUTTERFLY', 'An insect with colorful wings', 'medium', 
             'The butterfly landed gently on the flower.'),
            ('GUITAR', 'A stringed musical instrument', 'medium', 
             'She plays the guitar beautifully every evening.'),
            ('PENCIL', 'A writing instrument with graphite', 'medium', 
             'I used a pencil to sketch the landscape.'),
            ('GARDEN', 'A piece of ground for growing plants', 'medium', 
             'The garden blooms with flowers in spring.'),
            ('BRIDGE', 'A structure spanning a physical obstacle', 'medium', 
             'The bridge connects the two cities across the river.'),
            ('CASTLE', 'A large fortified building', 'medium', 
             'The medieval castle stands on top of the hill.'),
            ('PLANET', 'A celestial body orbiting a star', 'medium', 
             'Earth is the only planet known to support life.'),
            ('CRYSTAL', 'A clear transparent mineral', 'medium',
             'The crystal vase sparkled in sunlight.'),
            ('LIBRARY', 'A place where books are kept', 'medium',
             'Students study at the library daily.'),
            ('PICTURE', 'An image or photograph', 'medium',
             'We took a picture at the beach.'),
            ('KITCHEN', 'A room where food is prepared', 'medium',
             'Mom is cooking in the kitchen.'),
            ('TEACHER', 'Someone who instructs students', 'medium',
             'Our teacher explains things clearly.'),
            ('STUDENT', 'A person who is studying', 'medium',
             'The student works hard on homework.'),
            ('HOSPITAL', 'A place for medical treatment', 'medium',
             'She works at the hospital as a nurse.'),
            ('AIRPORT', 'A place where aircraft take off and land', 'medium',
             'We arrived at the airport early.'),
            ('STATION', 'A place where trains stop', 'medium',
             'The train arrives at the station soon.'),
            ('MARKET', 'A place where goods are sold', 'medium',
             'We shop at the farmers market weekly.'),
            ('OFFICE', 'A room for professional work', 'medium',
             'He goes to the office every morning.'),
            ('CINEMA', 'A theater where films are shown', 'medium',
             'We watched a movie at the cinema.'),
            ('MUSEUM', 'A building for displaying artifacts', 'medium',
             'The museum has ancient treasures.'),
            ('THEATER', 'A building for dramatic performances', 'medium',
             'We saw a play at the theater.'),
            ('CONCERT', 'A musical performance', 'medium',
             'The concert was amazing last night.'),
            ('FESTIVAL', 'A celebration or series of events', 'medium',
             'The music festival attracts thousands.'),
            ('PAINTING', 'A picture created with paint', 'medium',
             'The painting hung in the gallery.'),
            ('DRAWING', 'A picture made with pencil or pen', 'medium',
             'Her drawing skills are impressive.'),
            ('SCULPTURE', 'A three-dimensional work of art', 'medium',
             'The sculpture stands in the park.'),
            ('BUILDING', 'A structure with walls and a roof', 'medium',
             'The building has fifty floors.'),
            ('APARTMENT', 'A set of rooms for living in', 'medium',
             'They rent a small apartment downtown.'),
            ('BEDROOM', 'A room for sleeping', 'medium',
             'My bedroom is upstairs.'),
            ('BATHROOM', 'A room with a bath or shower', 'medium',
             'The bathroom has been renovated.'),
            ('CEILING', 'The upper interior surface of a room', 'medium',
             'The ceiling is painted white.'),
            ('BASEMENT', 'A room below ground level', 'medium',
             'We store boxes in the basement.'),
            ('BALCONY', 'A platform projecting from a building', 'medium',
             'The balcony has a beautiful view.'),
            ('CURTAIN', 'A piece of fabric hung to block light', 'medium',
             'Close the curtain please.'),
            ('BLANKET', 'A large piece of soft fabric', 'medium',
             'The blanket keeps me warm.'),
            ('PILLOW', 'A cushion for the head', 'medium',
             'This pillow is very comfortable.'),
            ('CARPET', 'A floor covering', 'medium',
             'The carpet is soft and clean.'),
            ('MIRROR', 'A reflective glass surface', 'medium',
             'She looked in the mirror.'),
            ('CABINET', 'A cupboard with shelves', 'medium',
             'Store dishes in the cabinet.'),
            ('DRAWER', 'A sliding storage compartment', 'medium',
             'Put it in the drawer.'),
            ('WALLET', 'A small case for holding money', 'medium',
             'I keep cards in my wallet.'),
            ('UMBRELLA', 'A device for protection from rain', 'medium',
             'Take an umbrella with you.'),
            
            # ========== HARD WORDS (50) ==========
            ('ALGORITHM', 'A step-by-step procedure for solving a problem', 'hard', 
             'The sorting algorithm efficiently organizes data.'),
            ('DATABASE', 'An organized collection of structured information', 'hard', 
             'The database stores millions of user records.'),
            ('JAVASCRIPT', 'A programming language for web browsers', 'hard', 
             'JavaScript adds interactivity to websites.'),
            ('ARCHITECTURE', 'The art and science of designing buildings', 'hard', 
             'The modern architecture of the building is impressive.'),
            ('ENCYCLOPEDIA', 'A comprehensive reference work', 'hard', 
             'I found detailed information in the encyclopedia.'),
            ('PHILOSOPHY', 'The study of fundamental questions about existence', 'hard', 
             'He studies ancient Greek philosophy at university.'),
            ('TECHNOLOGY', 'The application of scientific knowledge', 'hard', 
             'Technology continues to advance at a rapid pace.'),
            ('EDUCATION', 'The process of teaching and learning', 'hard', 
             'Quality education is the foundation of society.'),
            ('ADVENTURE', 'An exciting or unusual experience', 'hard', 
             'They embarked on an adventure across continents.'),
            ('CREATIVITY', 'The use of imagination to create something new', 'hard', 
             'Creativity and innovation drive human progress.'),
            ('DEMOCRACY', 'A system of government by the people', 'hard', 
             'Democracy ensures citizen participation in governance.'),
            ('REVOLUTION', 'A fundamental change in political power', 'hard', 
             'The industrial revolution transformed society.'),
            ('CHAMPION', 'A person who has defeated all opponents', 'hard', 
             'She became the champion after years of training.'),
            ('UNIVERSE', 'All existing matter and space', 'hard', 
             'Scientists study the origins of the universe.'),
            ('SYMPHONY', 'An elaborate musical composition', 'hard', 
             'The orchestra performed a beautiful symphony.'),
            ('VOCABULARY', 'All words known and used by a person', 'hard',
             'Reading expands your vocabulary significantly.'),
            ('DICTIONARY', 'A book that lists words alphabetically', 'hard',
             'I looked up the word in the dictionary.'),
            ('PHOTOGRAPHY', 'The art of taking photographs', 'hard',
             'She studied photography at art school.'),
            ('DEVELOPMENT', 'The process of developing or growing', 'hard',
             'Child development is a complex process.'),
            ('ENVIRONMENT', 'The surroundings or conditions', 'hard',
             'We must protect our environment for future generations.'),
            ('INFORMATION', 'Facts provided or learned', 'hard',
             'The information was very useful for my research.'),
            ('ORGANIZATION', 'An organized group of people', 'hard',
             'The organization helps children in need.'),
            ('ACHIEVEMENT', 'Something accomplished successfully', 'hard',
             'Graduating was a great achievement for him.'),
            ('RESTAURANT', 'A place where meals are served', 'hard',
             'We had dinner at a nice restaurant downtown.'),
            ('TELEVISION', 'A system for transmitting visual images', 'hard',
             'Television has changed how we consume media.'),
            ('GENERATION', 'All people born around the same time', 'hard',
             'Each generation has its own challenges.'),
            ('POPULATION', 'All inhabitants of a place', 'hard',
             'The city population continues to grow.'),
            ('BASKETBALL', 'A sport played with a ball and hoops', 'hard',
             'He plays basketball every weekend.'),
            ('COMMUNICATION', 'The exchange of information', 'hard',
             'Good communication improves relationships.'),
            ('EXTRAORDINARY', 'Very unusual or remarkable', 'hard',
             'She has extraordinary talent in music.'),
            ('MATHEMATICS', 'The study of numbers and shapes', 'hard',
             'Mathematics is essential for science.'),
            ('LITERATURE', 'Written works of artistic value', 'hard',
             'She studies English literature at college.'),
            ('MAGNIFICENT', 'Extremely beautiful or impressive', 'hard',
             'The view from the mountain was magnificent.'),
            ('CONSTELLATION', 'A group of stars forming a pattern', 'hard',
             'We identified several constellations in the night sky.'),
            ('RESPONSIBILITY', 'The state of being accountable', 'hard',
             'With great power comes great responsibility.'),
            ('INTELLIGENCE', 'The ability to acquire and apply knowledge', 'hard',
             'Emotional intelligence is very important.'),
            ('TRANSPORTATION', 'The movement of people or goods', 'hard',
             'Public transportation reduces traffic congestion.'),
            ('DISAPPOINTMENT', 'Sadness from unmet expectations', 'hard',
             'His failure was a great disappointment.'),
            ('APPRECIATION', 'Recognition of the value of something', 'hard',
             'I have appreciation for art and culture.'),
            ('CIVILIZATION', 'An advanced stage of human society', 'hard',
             'Ancient civilizations built amazing structures.'),
            ('CONSERVATION', 'The protection of natural resources', 'hard',
             'Wildlife conservation is crucial for biodiversity.'),
            ('DETERMINATION', 'Firmness of purpose', 'hard',
             'Her determination helped her succeed.'),
            ('ELECTRICITY', 'A form of energy from charged particles', 'hard',
             'Electricity powers our modern world.'),
            ('ENTERTAINMENT', 'Activity providing amusement', 'hard',
             'The show provided great entertainment.'),
            ('INVESTIGATION', 'A systematic inquiry', 'hard',
             'The investigation revealed new evidence.'),
            ('KINDERGARTEN', 'A school for young children', 'hard',
             'My daughter starts kindergarten next year.'),
            ('MANUFACTURING', 'The production of goods', 'hard',
             'Manufacturing jobs are important for the economy.'),
            ('NEIGHBORHOOD', 'A district within a town', 'hard',
             'Our neighborhood is very friendly.'),
            ('OPPORTUNITY', 'A favorable chance or occasion', 'hard',
             'This is a great opportunity for growth.'),
            ('PERSONALITY', 'The characteristics of a person', 'hard',
             'She has a wonderful personality.'),
        ]
        
        created_count = 0
        updated_count = 0
        
        for word, definition, difficulty, usage in words_data:
            obj, created = Word.objects.get_or_create(
                word=word,
                defaults={
                    'definition': definition,
                    'difficulty': difficulty,
                    'usage_example': usage
                }
            )
            
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'✓ Added: {word}'))
            else:
                # Update existing word if needed
                obj.definition = definition
                obj.difficulty = difficulty
                obj.usage_example = usage
                obj.save()
                updated_count += 1
                self.stdout.write(self.style.WARNING(f'↻ Updated: {word}'))
        
        self.stdout.write(self.style.SUCCESS(f'\n{"="*50}'))
        self.stdout.write(self.style.SUCCESS(f'Summary:'))
        self.stdout.write(self.style.SUCCESS(f'  • New words created: {created_count}'))
        self.stdout.write(self.style.SUCCESS(f'  • Existing words updated: {updated_count}'))
        self.stdout.write(self.style.SUCCESS(f'  • Total words in database: {Word.objects.count()}'))
        self.stdout.write(self.style.SUCCESS(f'{"="*50}\n'))
        
        # Display word count by difficulty
        easy_count = Word.objects.filter(difficulty='easy').count()
        medium_count = Word.objects.filter(difficulty='medium').count()
        hard_count = Word.objects.filter(difficulty='hard').count()
        
        self.stdout.write(self.style.SUCCESS('Words by difficulty:'))
        self.stdout.write(self.style.SUCCESS(f'  • Easy: {easy_count} words'))
        self.stdout.write(self.style.SUCCESS(f'  • Medium: {medium_count} words'))
        self.stdout.write(self.style.SUCCESS(f'  • Hard: {hard_count} words'))
        self.stdout.write(self.style.SUCCESS('\nWordOrbit is ready to play! 🎮'))